export enum UserRole {
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  ORG_ADMIN = "ORG_ADMIN",
  HR = "HR",
  MANAGER = "MANAGER",
  EMPLOYEE = "EMPLOYEE",
}

export enum AuditAction {
  VIEW = "VIEW",
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  EXPORT = "EXPORT",
  LOGIN = "LOGIN",
  INVITE = "INVITE",
  TRANSITION = "TRANSITION",
  UPLOAD = "UPLOAD",
  DOWNLOAD = "DOWNLOAD",
  SCHEDULE = "SCHEDULE",
  SEND = "SEND",
  ALERT = "ALERT",
  ACKNOWLEDGE = "ACKNOWLEDGE",
  REFER = "REFER",
}

export enum AuditEntity {
  ORGANISATION = "ORGANISATION",
  USER = "USER",
  EMPLOYEE = "EMPLOYEE",
  ROLE = "ROLE",
  AUDIT_LOG = "AUDIT_LOG",
  SICKNESS_CASE = "SICKNESS_CASE",
  FIT_NOTE = "FIT_NOTE",
  RTW_MEETING = "RTW_MEETING",
  GUIDANCE = "GUIDANCE",
  NOTIFICATION = "NOTIFICATION",
  TRIGGER_CONFIG = "TRIGGER_CONFIG",
  TRIGGER_ALERT = "TRIGGER_ALERT",
  OH_PROVIDER = "OH_PROVIDER",
  OH_REFERRAL = "OH_REFERRAL",
}

export enum OrganisationStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  DEACTIVATED = "DEACTIVATED",
}

export enum EmployeeStatus {
  ACTIVE = "ACTIVE",
  INVITED = "INVITED",
  DEACTIVATED = "DEACTIVATED",
}

export enum InvitationStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  EXPIRED = "EXPIRED",
}
